/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface StPaginate {
      'activeClassName': string;
      'breakClassName': string;
      'containerClassName': string;
      'disableInitialCallback': boolean;
      'disabledClassName': string;
      'extraAriaContext': string;
      'forcePage': number;
      'initialPage': number;
      'marginPagesDisplayed': number;
      'nextClassName': string;
      'nextLinkClassName': string;
      'pageClassName': string;
      'pageCount': number;
      'pageLinkClassName': string;
      'pageRangeDisplayed': number;
      'previousClassName': string;
      'previousLinkClassName': string;
      'showDefaultBreakLabel': boolean;
      'showDefaultNextLabel': boolean;
      'showDefaultPreviousLabel': boolean;
    }
  }

  interface HTMLStPaginateElement extends StencilComponents.StPaginate, HTMLStencilElement {}

  var HTMLStPaginateElement: {
    prototype: HTMLStPaginateElement;
    new (): HTMLStPaginateElement;
  };
  interface HTMLElementTagNameMap {
    'st-paginate': HTMLStPaginateElement;
  }
  interface ElementTagNameMap {
    'st-paginate': HTMLStPaginateElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'st-paginate': JSXElements.StPaginateAttributes;
    }
  }
  namespace JSXElements {
    export interface StPaginateAttributes extends HTMLAttributes {
      'activeClassName'?: string;
      'breakClassName'?: string;
      'containerClassName'?: string;
      'disableInitialCallback'?: boolean;
      'disabledClassName'?: string;
      'extraAriaContext'?: string;
      'forcePage'?: number;
      'initialPage'?: number;
      'marginPagesDisplayed'?: number;
      'nextClassName'?: string;
      'nextLinkClassName'?: string;
      'onOnPageChange'?: (event: CustomEvent) => void;
      'pageClassName'?: string;
      'pageCount'?: number;
      'pageLinkClassName'?: string;
      'pageRangeDisplayed'?: number;
      'previousClassName'?: string;
      'previousLinkClassName'?: string;
      'showDefaultBreakLabel'?: boolean;
      'showDefaultNextLabel'?: boolean;
      'showDefaultPreviousLabel'?: boolean;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
